##
# Copy DB from prod to uat.

name: Copy DB from production to uat

trigger: none

variables:
  - group: db
  - name: destinationDatabase
    value: db_uat

stages:
  - stage: replace_db
    displayName: Copy DB from production to UAT
    jobs:
      - job: create_and_copy_db_dump
        displayName: Create and copy database dump
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: bash@3
            displayName: Replace database
            inputs:
              targetType: inline
              script: |
                mysqldump --ssl-ca=/etc/ssl/certs/DigiCert_Global_Root_CA.pem -u $(AZURE_MYSQL_USERNAME) -p"$(AZURE_MYSQL_PASSWORD)" -h $(AZURE_MYSQL_HOST) $(AZURE_MYSQL_DBNAME) > dump.sql
                mysql --ssl-ca=/etc/ssl/certs/DigiCert_Global_Root_CA.pem -u $(AZURE_MYSQL_USERNAME) -p"$(AZURE_MYSQL_PASSWORD)" -h $(AZURE_MYSQL_HOST) $(destinationDatabase) < dump.sql
