##
# Copy DB from prod to uat.

name: Copy DB from production to uat

trigger: none

variables:
  - group: db
  - name: AZURE_MYSQL_DBNAME
    value: db_prod

stages:
  - stage: copy_db
    displayName: Copy DB from producyion to UAT
    jobs:
      - job: create_and_copy_db_dump
        displayName: Create and copy database dump
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: bash@3
            displayName: Create database dump
            name: create_db_dump
            inputs:
              targetType: inline
              script: |
                set -e
                mysqldump --ssl-ca=/etc/ssl/certs/DigiCert_Global_Root_CA.pem -u $(AZURE_MYSQL_USERNAME) -p"$(AZURE_MYSQL_PASSWORD)" -h $(AZURE_MYSQL_HOST) $(AZURE_MYSQL_DBNAME) > dump.sql
                ls -la
                printenv
