##
# Deploy image to web app slot.
#
# This template requires the following variables:
#   - resourceManagerServiceConnection => Resource manager connection ID.
#   - resourceGroupName => Name of Azure resource groupn the web app lives in.
#   - webAppName => Name of Azure web app.
#   - deploySlot => Web app slot to deploy to.
#   - containerRegistry => Container registry name.
#   - imageRepository => Repository in Docker container registry.
#   - deployEnvironment => Environment to build; main, dev or uat.

stages:

  # Deploy Docker image to web app.
  - stage: Deploy
    displayName: Deploy Drupal image.
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          - task: AzureRmWebAppDeployment@5
            displayName: Deploy image
            inputs:
              azureSubscription: $(resourceManagerServiceConnection)
              ResourceGroupName: $(resourceGroupName)
              appType: webAppContainer
              WebAppName: $(webAppName)
              deployToSlotOrASE: true
              SlotName: $(deploySlot)
              DockerNamespace: $(containerRegistry)
              DockerRepository: $(imageRepository)
              DockerImageTag: $(deployEnvironment)

          - task: AzureAppServiceManage@0
            displayName: Restart container
            inputs:
              azureSubscription: $(resourceManagerServiceConnection)
              ResourceGroupName: $(resourceGroupName)
              WebAppName: $(webAppName)
              SpecifySlotOrASE: true
              Slot: $(deploySlot)
              Action: 'Restart Azure App Service'
