##
# Deploy WebApp pipeline template.

stages:
  # Deploy Docker image to web app.
  - stage: Deploy
    displayName: Deploy Drupal image.
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureRmWebAppDeployment@5
            displayName: Deploy image
            inputs:
              azureSubscription: $(resourceManagerServiceConnection)
              ResourceGroupName: $(resourceGroupName)
              appType: webAppContainer
              WebAppName: $(webAppName)
              SlotName: $(deploySlot)
              deployToSlotOrASE: true
              DockerNamespace: $(containerRegistry)
              DockerRepository: $(imageRepository)
              DockerImageTag: $(deployEnvironment)
