##
# Switch web app slots.

stages:

  # Switch container between slots.
  - stage: finalise
    displayName: Switch slots
    jobs:
      - job: Switch
        displayName: Switch
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          - task: AzureAppServiceManage@0
            displayName: Switch slot
            inputs:
              azureSubscription: $(resourceManagerServiceConnection)
              ResourceGroupName: $(resourceGroupName)
              WebAppName: $(webAppName)
              SourceSlot: $(sourceSlot)
              TargetSlot: $(targetSlot)
              Action: 'Swap Slots'
