##
# Build uat branch and deploy to the uat slot.

name: Build and deploy uat branch to uat slot

trigger:
  - uat

variables:
  - group: azure-resources
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/azure-web-app/Dockerfile'
  - name: deployEnvironment
    value: $(Build.SourceBranchName)
  - name: deploySlot
    value: 'app-slot-uat'
  - name: environment
    value: 'uat'

stages:
  - template: templates/build.yml
  - template: templates/deploy.yml
