##
# Build main branch and deploy to the preprod slot.

name: Build and deploy main branch to preprod slot

trigger: none

variables:
  - group: azure-resources
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/azure-web-app/Dockerfile'
  - name: deployEnvironment
    value: $(Build.SourceBranchName)
  - name: deploySlot
    value: 'app-slot-preprod'
  - name: environment
    value: 'production'

stages:
  - template: templates/build.yml
  - template: templates/deploy.yml
