##
# Build dev branch and deploy to the dev slot.

name: Build and deploy dev branch to dev slot

trigger:
  - dev

variables:
  - group: azure-resources
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/azure-web-app/Dockerfile'
  - name: deployEnvironment
    value: $(Build.SourceBranchName)
  - name: deploySlot
    value: 'app-slot-dev'
  - name: environment
    value: 'dev'

stages:
  - template: templates/build.yml
  - template: templates/deploy.yml
