##
# Deploy main image.

name: Deploy main image to preprod slot

trigger: none

variables:
  - group: azure-resources
  - name: deployEnvironment
    value: 'main'
  - name: deploySlot
    value: 'app-slot-preprod'

stages:
  - template: templates/deploy.yml
