##
# Finalise main deploy by swicthing preprod slot to production.

name: Finalise main deploy

trigger: none

variables:
  - group: azure-resources
  - name:  sourceSlot
    value: 'app-slot-preprod'
  - name:  targetSlot
    value: 'production'

stages:
  - template: templates/switch-slot.yml
