##
# Replace dev database with production.

name: Replace dev database with production.

trigger: none

variables:
  - group: db
  - name: sourceDatabase
    value: $[variables.productionDatabase]
  - name: destinationDatabase
    value: $[variables.devDatabase]

stages:
  - template: templates/replace-database.yml
